on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 16
    # - name: Python version
    #   run: python --version
    # - name: Remove gyp dependencies
    #   run: |
    #       rm -rf node_modules package-lock.json

    # - name: Remove node-sass
    #   run: npm uninstall node-sass
    #   continue-on-error: true
      
    # - name: Install build tools for node-gyp
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y python3 g++ make build-essential
    #     echo python --version
        
    # - name: Clean node_modules
    #   run: |
    #     rm -rf node_modules package-lock.json
    #     npm install
    #   continue-on-error: true

    - name: Install Node.js dependencies
      run: npm install
      continue-on-error: true
    #   # If your frontend is in a subfolder (like 'frontend'), add 'working-directory: ./frontend'

    - name: Build Node.js project
      run: npm run build
      # If your frontend is in a subfolder, add 'working-directory: ./frontend'
